name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v5
        with:
          persist-credentials: false 

      - name: Install and Build 🔧
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npm install
          npm run docs:build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository-name: mynodebtc/mynodebtc.github.io
          branch: master
          folder: docs/.vuepress/dist
